### ISSUE TITLE
Please allow to specify an ouput mode for timidity, or to set the midi player with options completely

### ISSUE THREAD

**Issue by Bracket-H** [sersorrel/vim-lilypond#1]
Changing the binds after the fact is a pain...

**Comment by sersorrel** [comment]
I don't actually maintain this plugin, sorry – you're best off submitting your issues to the upstream LilyPond project (e.g. via one of the [mailing lists](https://lilypond.org/contact.html)). I just mirror the Vim plugin files to GitHub to make it marginally easier to use.
